services:
- type: web
  name: streamlit-app

  runtime: python
  region: oregon
  buildCommand: "pip install -r requirements.txt"
  startCommand: "streamlit run app.py --server.port $PORT"
  plan: free
